In [333]:
import pandas as pd
import numpy as np

data=pd.read_csv("dataset/x_train.csv")
y=pd.read_csv("dataset/y_train.csv")

## PART 1: Data Visualization

In [334]:
print(data.shape)
print(y.shape)

(328135, 322)
(328135, 2)

In [335]:
pd.set_option("display.max_columns", None)
data=data.set_index("Id")
data.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,53,11,11162015,11,16,2015,1100,2015015629,2015015629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,NaN,1.0,1.0,2.0,2.0,1.0,5,88.0,1,1,2.0,1.0,3.0,NaN,1,1.0,2.0,2,2,NaN,2.0,2,2,2.0,1,2,3.0,NaN,2,1,5,1,NaN,NaN,NaN,2.0,1,88.0,8.0,1.0,110.0,501.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,3.0,888.0,NaN,NaN,NaN,555.0,205.0,304.0,303.0,308.0,205.0,1.0,64.0,102.0,30.0,98.0,220.0,30.0,105.0,NaN,NaN,NaN,NaN,1.0,1.0,102015.0,8.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,5.0,2.0,NaN,1.0,NaN,NaN,1.0,4.0,1.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,1.0,NaN,532049,120.931680,1.0,120.931680,NaN,NaN,NaN,NaN,2,0.233948,264.741181,1,1,1,1,1.0,1,1,3,2.0,1,1,2,1,1,1,1.0,8,1,57,5,61.0,1.55,49.90,20.78,2.0,1,1,3,5,1,2,2,0,1,0,1,0.00,0.71,0.13,0.10,0.27,0.71,0,0,1,1,0.71,1.21,2,1,1,1,0,0,1,3.5,4.5,26.91,4.61,1.0,1.0,30.0,30.0,2.000,4.667,60.0,140.0,5.000,0,60.0,140.0,200.0,0.0,0.0,0.0,2,1,1,2,2,1,1,1,3.0,3.0,4.0,1,1,NaN,NaN,2.0
1,33,12,12152015,12,15,2015,1200,2015004387,2015004387,1.0,1.0,NaN,1.0,1.0,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,88.0,88,NaN,1,1,2.0,1.0,1.0,1.0,1,1.0,2.0,2,2,NaN,2.0,2,2,2.0,2,2,3.0,NaN,1,1,4,1,2.0,NaN,1.0,2.0,1,88.0,7.0,2.0,200.0,510.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,107.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,5.0,331071,13.467336,2.0,26.934672,9.0,NaN,NaN,NaN,1,0.786572,160.771560,2,1,2,1,1.0,1,1,3,2.0,1,1,2,1,1,1,1.0,8,1,57,5,70.0,1.78,90.72,28.70,3.0,2,1,2,5,1,2,1,100,9,99900,9,NaN,NaN,NaN,NaN,NaN,NaN,2,4,0,0,NaN,NaN,9,9,1,1,1,1,9,NaN,NaN,28.65,4.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,9,9,9,9,9,9,9,9,3.0,3.0,4.0,9,9,NaN,NaN,NaN
2,20,10,10202015,10,20,2015,1100,2015005638,2015005638,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,77.0,77,88.0,1,1,2.0,1.0,3.0,NaN,1,1.0,1.0,2,2,NaN,2.0,2,2,1.0,2,2,3.0,NaN,2,1,6,1,2.0,NaN,1.0,2.0,1,88.0,99.0,1.0,9999.0,507.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,NaN,7.0,3.0,204.0,1.0,88.0,2.0,301.0,102.0,203.0,101.0,203.0,101.0,1.0,64.0,103.0,30.0,88.0,NaN,NaN,888.0,2.0,2.0,3.0,5.0,1.0,1.0,102015.0,5.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,1.0,1.0,201091,12.370176,2.0,24.740353,9.0,NaN,NaN,NaN,1,0.669767,54.508965,1,9,1,1,2.0,1,1,3,1.0,1,1,2,1,1,1,1.0,10,2,65,6,67.0,1.70,NaN,NaN,NaN,9,1,4,9,3,1,1,13,1,93,1,0.03,2.00,0.43,1.00,0.43,1.00,0,0,1,1,2.03,2.86,1,1,1,1,0,0,1,3.5,0.0,23.95,4.11,1.0,0.0,30.0,NaN,3.000,NaN,90.0,0.0,0.000,0,90.0,0.0,90.0,0.0,0.0,0.0,3,2,2,2,2,2,4,2,2.0,2.0,3.0,1,1,1.0,2.0,2.0
3,42,6,6182015,6,18,2015,1100,2015004694,2015004694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,NaN,1.0,2.0,2.0,1.0,88.0,88,NaN,1,1,2.0,1.0,3.0,NaN,1,4.0,2.0,2,2,NaN,2.0,2,2,1.0,2,2,3.0,NaN,2,1,4,1,NaN,NaN,NaN,2.0,7,88.0,99.0,2.0,168.0,505.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,3.0,888.0,NaN,NaN,NaN,555.0,555.0,302.0,101.0,205.0,101.0,1.0,98.0,105.0,200.0,31.0,101.0,300.0,201.0,2.0,2.0,3.0,3.0,1.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,1.0,NaN,422039,213.645885,1.0,213.645885,9.0,NaN,NaN,NaN,9,NaN,532.653080,1,9,1,2,1.0,1,1,3,1.0,1,1,2,1,1,1,1.0,10,2,65,6,65.0,1.65,76.20,27.96,3.0,2,1,2,9,1,2,2,0,1,0,1,0.00,0.00,0.07,1.00,0.71,1.00,0,0,1,1,0.00,2.78,2,1,1,1,0,0,1,4.5,5.5,23.95,4.11,2.0,2.0,120.0,180.0,5.000,1.000,600.0,180.0,0.233,0,1200.0,360.0,1560.0,600.0,180.0,780.0,1,1,1,1,1,2,2,2,2.0,2.0,3.0,1,1,2.0,2.0,2.0
4,24,11,11062015,11,6,2015,1100,2015004673,2015004673,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,88.0,88,NaN,1,9,2.0,1.0,3.0,NaN,1,3.0,2.0,2,2,NaN,2.0,2,2,2.0,2,2,3.0,NaN,1,9,9,1,2.0,NaN,1.0,1.0,9,88.0,99.0,1.0,190.0,602.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,9.0,NaN,NaN,9.0,999.0,NaN,NaN,NaN,101.0,315.0,315.0,304.0,308.0,325.0,1.0,64.0,220.0,100.0,76.0,777.0,100.0,888.0,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,1.0,1.0,241011,26.493114,1.0,26.493114,9.0,NaN,NaN,NaN,1,0.920562,561.526324,1,9,1,1,1.0,1,1,3,2.0,1,1,2,1,1,1,1.0,14,3,61,5,74.0,1.88,86.18,24.39,2.0,1,1,9,9,9,9,9,900,9,99900,9,1.00,0.50,0.50,0.13,0.27,0.83,0,0,1,1,1.50,1.73,1,1,1,1,0,0,1,3.5,4.0,999.00,999.00,NaN,NaN,60.0,60.0,4.667,NaN,280.0,NaN,0.000,1,NaN,NaN,NaN,NaN,NaN,NaN,9,9,9,9,9,2,9,9,3.0,3.0,4.0,1,1,9.0,9.0,2.0

In [336]:
y=y.set_index("Id")
y.head()

    _MICHD
Id
0       -1
1       -1
2       -1
3       -1
4       -1

Detect nas % in columns

In [337]:
nas=pd.isna(data)
nas=nas.sum(axis=0)/data.shape[0]*100
nas.index=data.columns
nas=nas.to_frame(name="missing_perc")
nas=nas.sort_values("missing_perc",ascending=False)
nas

          missing_perc
COLGHOUS     99.990248
LADULT       99.990248
PCDMDECN     99.945449
ASDRVIST     99.930516
ASERVIST     99.930516
...                ...
_AGEG5YR      0.000000
_RACEGR3      0.000000
_RACEG21      0.000000
_RACE         0.000000
_STATE        0.000000

[321 rows x 1 columns]

We notice that only a few data columns are not sparse (less than half)

In [338]:

keep_sparse = [
    "INSULIN",
    "DIABEYE",
    "CVDASPRN",
    "WTCHSALT",
    "DRADVISE",
]

drop_cols=nas.index[nas["missing_perc"] > 90 & ~nas.index.isin(keep_sparse)]

data_reduced = data.drop(columns=drop_cols)

data_reduced.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,MENTHLTH,HLTHPLN1,PERSDOC2,BLOODCHO,CVDSTRK3,ASTHMA3,CHCOCNCR,CHCCOPD1,ADDEPEV2,CHCKIDNY,SEX,MARITAL,EDUCA,RENTHOM1,EMPLOY1,QSTVER,_STSTR,_RAWRAKE,_WT2RAKE,_DUALUSE,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_LTASTH1,_CASTHM1,_ASTHMS1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,MAXVO2_,FC60_,PAMISS1_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_RFSEAT2,_RFSEAT3
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,53,11,11162015,11,16,2015,1100,2015015629,2015015629,5,1,1,1,2,2,2,2,1,2,2,1,5,1,1,20,532049,1.0,120.931680,2,264.741181,1,1,1,1,1,1,3,1,1,2,1,1,1,8,1,57,5,1,1,3,5,1,2,2,0,1,0,1,0,0,1,1,2,1,1,1,0,0,1,26.91,4.61,0,2,1,1,2,2,1,1,1,1,1
1,33,12,12152015,12,15,2015,1200,2015004387,2015004387,88,1,1,1,2,2,2,2,2,2,1,1,4,1,1,10,331071,2.0,26.934672,1,160.771560,2,1,2,1,1,1,3,1,1,2,1,1,1,8,1,57,5,2,1,2,5,1,2,1,100,9,99900,9,2,4,0,0,9,9,1,1,1,1,9,28.65,4.91,9,9,9,9,9,9,9,9,9,9,9
2,20,10,10202015,10,20,2015,1100,2015005638,2015005638,77,1,1,1,2,2,2,2,2,2,2,1,6,1,1,11,201091,2.0,24.740353,1,54.508965,1,9,1,1,1,1,3,1,1,2,1,1,1,10,2,65,6,9,1,4,9,3,1,1,13,1,93,1,0,0,1,1,1,1,1,1,0,0,1,23.95,4.11,0,3,2,2,2,2,2,4,2,1,1
3,42,6,6182015,6,18,2015,1100,2015004694,2015004694,88,1,1,1,2,2,2,2,2,2,2,1,4,1,7,20,422039,1.0,213.645885,9,532.653080,1,9,1,2,1,1,3,1,1,2,1,1,1,10,2,65,6,2,1,2,9,1,2,2,0,1,0,1,0,0,1,1,2,1,1,1,0,0,1,23.95,4.11,0,1,1,1,1,1,2,2,2,1,1
4,24,11,11062015,11,6,2015,1100,2015004673,2015004673,88,1,9,1,2,2,2,2,2,2,1,9,9,1,9,11,241011,1.0,26.493114,1,561.526324,1,9,1,1,1,1,3,1,1,2,1,1,1,14,3,61,5,1,1,9,9,9,9,9,900,9,99900,9,0,0,1,1,1,1,1,1,0,0,1,999.00,999.00,1,9,9,9,9,9,2,9,9,1,1

In [339]:
data_reduced=data_reduced.drop(["IDATE"],axis=1)

In [340]:
drop_cols = [
    "SEQNO",
    "_PSU",

    # interview date / survey administration
    "FMONTH",
    "IMONTH",
    "IDAY",
    "IYEAR",
    "DISPCODE",
    "QSTVER",

    # BRFSS sampling / weighting machinery
    "_STSTR",
    "_RAWRAKE",
    "_WT2RAKE",
    "_DUALUSE",
    "_LLCPWT",
]

data_reduced = data_reduced.drop(columns=drop_cols)
data_reduced.head()

,_STATE,MENTHLTH,HLTHPLN1,PERSDOC2,BLOODCHO,CVDSTRK3,ASTHMA3,CHCOCNCR,CHCCOPD1,ADDEPEV2,CHCKIDNY,SEX,MARITAL,EDUCA,RENTHOM1,EMPLOY1,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_LTASTH1,_CASTHM1,_ASTHMS1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,MAXVO2_,FC60_,PAMISS1_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_RFSEAT2,_RFSEAT3
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,53,5,1,1,1,2,2,2,2,1,2,2,1,5,1,1,1,1,1,1,1,1,3,1,1,2,1,1,1,8,1,57,5,1,1,3,5,1,2,2,0,1,0,1,0,0,1,1,2,1,1,1,0,0,1,26.91,4.61,0,2,1,1,2,2,1,1,1,1,1
1,33,88,1,1,1,2,2,2,2,2,2,1,1,4,1,1,2,1,2,1,1,1,3,1,1,2,1,1,1,8,1,57,5,2,1,2,5,1,2,1,100,9,99900,9,2,4,0,0,9,9,1,1,1,1,9,28.65,4.91,9,9,9,9,9,9,9,9,9,9,9
2,20,77,1,1,1,2,2,2,2,2,2,2,1,6,1,1,1,9,1,1,1,1,3,1,1,2,1,1,1,10,2,65,6,9,1,4,9,3,1,1,13,1,93,1,0,0,1,1,1,1,1,1,0,0,1,23.95,4.11,0,3,2,2,2,2,2,4,2,1,1
3,42,88,1,1,1,2,2,2,2,2,2,2,1,4,1,7,1,9,1,2,1,1,3,1,1,2,1,1,1,10,2,65,6,2,1,2,9,1,2,2,0,1,0,1,0,0,1,1,2,1,1,1,0,0,1,23.95,4.11,0,1,1,1,1,1,2,2,2,1,1
4,24,88,1,9,1,2,2,2,2,2,2,1,9,9,1,9,1,9,1,1,1,1,3,1,1,2,1,1,1,14,3,61,5,1,1,9,9,9,9,9,900,9,99900,9,0,0,1,1,1,1,1,1,0,0,1,999.00,999.00,1,9,9,9,9,9,2,9,9,1,1

:TODO transform state variable into dummy variable (!Use one hot coding)

In [341]:
data_reduced=data_reduced-data_reduced.mean()
data_reduced=data_reduced/data_reduced.std()
data_reduced["intercept"]=np.ones(len(data_reduced))

FIRST TEST OF REGRESSION:
part 1 split into train and validation

In [342]:
x_train = data_reduced.sample(frac=0.8, random_state=21)
x_validation = data_reduced.drop(index=x_train.index)
y_train = y.loc[x_train.index]
y_validation = y.loc[x_validation.index]
y_train = y_train.to_numpy().ravel()
y_validation = y_validation.to_numpy().ravel()

linear logistic regression

In [343]:
print(x_train.shape)
print(y_train.shape)
print(type(x_train))
print(type(y_train))

(262508, 69)
(262508,)
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>

In [344]:
def sigmoid(t):
    t = np.clip(t, -500, 500)
    return 1 / (1 + np.exp(-t))


def transform_y(y):
    return (y==1).astype(int)

y_train=transform_y(y_train)
y_validation=transform_y(y_validation)



def logistic_reg_regularized(y,x,w,max_iters,gamma,_lambda):
    for i in range(max_iters):

        p = sigmoid(x @ w)
        grad = x.T @ (p - y) / len(y) + 2*_lambda*w
        w -= gamma * grad
    return w

In [345]:
w = np.zeros(x_train.shape[1])
w = logistic_reg_regularized(
    y_train,
    x_train,
    w,
    max_iters=1000,
    gamma=0.1,
    _lambda=0.0,
)

train_probs = sigmoid(x_train @ w)
val_probs = sigmoid(x_validation @ w)

train y mean: 0.08813445685464824
train p mean: 0.0902476681163836
val y mean: 0.08897252655157176
val p mean: 0.09096147194149183

In [346]:
thresholds = np.linspace(0, 1, 20)
threshold_scores = []

for threshold in thresholds:
    prediction = (val_probs >= threshold).astype(int)
    score = np.mean(y_validation == prediction)
    threshold_scores.append(score)

    print(f"threshold: {threshold:.3f} | accuracy: {score:.6f}")

threshold: 0.000 | accuracy: 0.088973
threshold: 0.053 | accuracy: 0.574215
threshold: 0.105 | accuracy: 0.741875
threshold: 0.158 | accuracy: 0.826855
threshold: 0.211 | accuracy: 0.870998
threshold: 0.263 | accuracy: 0.893017
threshold: 0.316 | accuracy: 0.903744
threshold: 0.368 | accuracy: 0.908300
threshold: 0.421 | accuracy: 0.909748
threshold: 0.474 | accuracy: 0.910448
threshold: 0.526 | accuracy: 0.910814
threshold: 0.579 | accuracy: 0.910357
threshold: 0.632 | accuracy: 0.910281
threshold: 0.684 | accuracy: 0.910372
threshold: 0.737 | accuracy: 0.910601
threshold: 0.789 | accuracy: 0.910753
threshold: 0.842 | accuracy: 0.910784
threshold: 0.895 | accuracy: 0.910967
threshold: 0.947 | accuracy: 0.911027
threshold: 1.000 | accuracy: 0.911027